- name: course information
  hosts: local
  connection: local
  vars:
    course: "aws devops"
    duration_in_hrs: 150 
    is_live_sessions: true
    topics:
     - linux
     - shell
     - ansible
    more_details: 
      months: "5"
      trainer: "siva"
  tasks:
  - name: pint information
    debug:
      msg: 
       name: {{course}}
       duration: {{duration_in_hrs}}
       live sessions: {{is_live_sessions}}
       topics: {{topics}}
       trainer and course duration details: {{more_details}}