[frontend]
##172.31.12.210 COURSE="devops", TRAINER=siva, DURATION=150hrs
##172.31.14.212 COURSE="devops", TRAINER=siva, DURATION=150hrs

[local]
localhost

#local group vars
[local:vars]
; COURSE="devops"
; TRAINER="Siva"
; DURATION="150HRS"