[frontend]
172.31.12.210 ;COURSE="devops", TRAINER=siva, DURATION=150hrs



;172.31.14.212 ;COURSE="devops", TRAINER=siva, DURATION=150hrs

[local]
localhost

#local group vars
[local:vars]
; COURSE="devops"
; TRAINER="Siva"
; DURATION="150HRS"

[mongodb]
mongodb.daws90.fun

[redis]
redis.daws90.fun

[mysql]
mysql.daws90.fun

[rabbitmq]
rabbitmq.daws90.fun

[catalogue]
catalogue.daws90.fun


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
