- name: demo on inventory variables
  hosts: local 
  connection: local
  tasks:
   - name: print data
     debug:
      msg: "hi, i am learning {{COURSE}}, My trainer is {{TRAINER}}, duration is {{DURATION}}"