- name: demo on var_files
  hosts: local
  connection: local
  var_files:
  - course.yaml
  tasks:
  - name: print information
    debug:
    msg: "hi, i am learning {{COURSE}}, My trainer is {{TRAINER}}, duration is {{DURATION}}"
  